[package]
disabled = true
[python]
disabled = true
[rust]
disabled = true
[vagrant]
disabled = true
[lua]
disabled = true
[nodejs]
disabled = true
[cmake]
disabled = true
[perl]
disabled = true
[c]
disabled = true
[rlang]
disabled = true
